# Generated by Django 2.2 on 2019-06-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='added_on',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='entry_amount',
        ),
    ]
