# Generated by Django 4.2.7 on 2023-11-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20190602_0119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Entry',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='date_posted',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_amount',
            new_name='amount',
        ),
    ]
