# Generated by Django 4.2.7 on 2023-11-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_journalentrytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentrytemplate',
            name='name',
            field=models.CharField(default='Receive Rental Payment', max_length=100),
            preserve_default=False,
        ),
    ]
