# Generated by Django 4.2.7 on 2023-11-20 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_journalentrytemplate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(default=datetime.date(2023, 11, 20)),
            preserve_default=False,
        ),
    ]
