# Generated by Django 4.2.7 on 2023-11-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_journalentry_entry_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='journal_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.journalentry'),
        ),
    ]
