# Generated by Django 4.2.7 on 2023-11-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_entry_journal_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Transaction',
        ),
    ]
